sudo: required

#language: php

services:
  - docker
  
branches:
  only: 
    - master
    - staging-ci

before_script:
  - docker build -t docker-moodle .

script:
- docker ps

notifications:
  slack: diorama-radio:JaoyLeAlhZ8e6ugkadHEdteG
